new_fashion_P/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from mysite.core import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('closet/', views.closet, name='closet'),
    path('add_clothing', views.add_clothing, name='add_clothing'),
    path('clothings/<int:pk>/', views.delete_clothing, name='delete_clothing'),
    path('coordinate/<int:pk>/',
         views.coordinate_clothing, name='coordinate_clothing'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

new_fashion_P/mysite/core/models.py
from django.db import models
from django.contrib.auth.models import User





class Member(models.Model):
    # user와 1대1 매칭
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="member")
    name = models.CharField(max_length=10)



class Clothing(models.Model):
    owner = models.ForeignKey(
        Member, on_delete=models.SET_NULL, null=True, related_name="clothing")
    image = models.ImageField(upload_to='clothings/images/')



    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)


class CoordinateClothing(models.Model):
    c_kind = models.IntegerField()
    c_image = models.ImageField(blank=True)
    c_url = models.CharField(max_length=200, blank=True)

new_fashion_P/mysite/core/forms.py
from django import forms

from .models import Clothing


class ClothingForm(forms.ModelForm):
    class Meta:
        model = Clothing
        fields = ('owner','image')

new_fashion_P/mysite/core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView
from django.contrib.auth.decorators import login_required
from .forms import ClothingForm
from .models import Member, Clothing, CoordinateClothing
from .coordinate_clothings import fashion_tools, recommend, resize_with_padding
from PIL import Image, ImageOps
import cv2
import numpy as np
import tensorflow as tf
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
ERROR_MSG = {
    'ID_EXIST': '이미 사용 중인 아이디 입니다.',
    'ID_NOT_EXIST': '존재하지 않는 아이디 입니다.',
    'ID_PW_MISSING': '아이디와 비밀번호를 다시 확인해주세요.',
    'PW_CHECK': '비밀번호가 일치하지 않습니다.',

}

# 비로그인 시 첫화면으로 리다이렉트 시킴
# URL_LOGIN = '/'


class Home(TemplateView):
    template_name = 'index.html'


def signup(request):


    context = {
        'error': {
            'state': False,
            'msg': ''
        }
    }

    if request.method == "POST":

        user_id = request.POST['user_id']
        user_pw = request.POST['user_pw']
        user_pw_check = request.POST['user_pw_check']

        # 추가
        name = request.POST['name']

        if (user_id and user_pw):

            user = User.objects.filter(username=user_id)

            if len(user) == 0:

                if user_pw == user_pw_check:

                    created_user = User.objects.create_user(
                        username=user_id,
                        password=user_pw
                    )

                    # 추가
                    Member.objects.create(
                        user=created_user,
                        name=name,
                    )

                    auth.login(request, created_user)
                    loginUser = Member.objects.get(user=created_user)
                    print(loginUser.id)
                    request.session['user'] = loginUser.id

                    return redirect('home')

                else:
                    context['error']['state'] = True
                    context['error']['msg'] = ERROR_MSG['PW_CHECK']
            else:
                context['error']['state'] = True
                context['error']['msg'] = ERROR_MSG['ID_EXIST']

        else:
            context['error']['state'] = True
            context['error']['msg'] = ERROR_MSG['ID_PW_MISSING']

    return render(request, 'home.html', context)

def login(request):

    context = {
        'error': {
            'state': False,
            'msg': ''
        },
    }
    if request.method == 'POST':

        user_id = request.POST['user_id']
        user_pw = request.POST['user_pw']

        user = User.objects.filter(username=user_id)

        if (user_id and user_pw):
            if len(user) != 0:

                user = auth.authenticate(
                    username=user_id,
                    password=user_pw
                )
                if user != None:
                    auth.login(request, user)
                    loginUser = Member.objects.get(user=user)
                    print(loginUser.id)
                    request.session['user'] = loginUser.id

                    return redirect('home')
                else:
                    context['error']['state'] = True
                    context['error']['msg'] = ERROR_MSG['PW_CHECK']
            else:
                context['error']['state'] = True
                context['error']['msg'] = ERROR_MSG['ID_NOT_EXIST']
        else:
            context['error']['state'] = True
            context['error']['msg'] = ERROR_MSG['ID_PW_MISSING']
    return render(request, 'home.html', context)


def logout(request):
    auth.logout(request)
    return redirect('home')


# @login_required(login_url=URL_LOGIN)
def closet(request):
    clothings = Clothing.objects.all()
    return render(request, 'closet.html', {
        'clothings': clothings
    })

# @login_required(login_url=URL_LOGIN)
def add_clothing(request):
    if request.method == 'POST':
        form = ClothingForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('closet')
    else:
        form = ClothingForm()
    return render(request, 'add_clothing.html', {
        'form': form
    })

# @login_required(login_url=URL_LOGIN)
def delete_clothing(request, pk):
    if request.method == 'POST':
        clothing = Clothing.objects.get(pk=pk)
        clothing.delete()
    return redirect('closet')

# @login_required(login_url=URL_LOGIN)
def coordinate_clothing(request, pk):
    if request.method == 'POST':
        clothing = Clothing.objects.get(pk=pk)

        # 모델 임포트 후 의상 부분만 추출하는 코드.
        # 훈련된 모델 가지고 오는 경로 설정.
        saved = tf.keras.models.load_model('./mysite/core/train_models/topwears.h5', custom_objects={'tf': tf})
        f = '.' + clothing.image.url
        print(f)
        img = Image.open(f)
        img = resize_with_padding(img, (750, 750))
        img = np.array(img)

        ###running code
        api = fashion_tools(img, saved)
        image = api.get_dress(True)

        # 이미지 자르고, 투명값 검정배경 입혀주기.
        image_crop = image[:, 512:]
        image_crop = np.uint8(image_crop)

        for i in image_crop:
            for j in i:
                if j[3] < 40:
                    j[0] = 0
                    j[1] = 0
                    j[2] = 0

        # 리사이즈 인풋값 맞춰 주기.
        image_resize = cv2.resize(image_crop, (28, 28))

        # 그레이 스케일.. 후 픽셀 출력..
        image_gray = cv2.cvtColor(image_resize, cv2.COLOR_BGRA2GRAY)

        # 정규화 해준다.
        input_image = image_gray / 255.0

        # input값이 3차원 이여서 차원을 늘려준다.
        input_image = np.reshape(input_image, (1, 28, 28, 1))

        # 저장된 훈련모델 불러오는 방법
        model = tf.keras.models.load_model('./mysite/core/train_models/fAIshion_P_T9.h5', custom_objects={'tf': tf})

        # 예측 수행
        input_predict = model.predict(input_image) + 1
        print(input_predict)

        # 예측 결과 확인
        max_value = np.max(input_predict)
        max_idx = np.where(input_predict == max_value)
        predict_idx = max_idx[1][0]
        print(predict_idx)

        ## 여기까지 오케이 ^_^

        # recommend return 값 받기
        result = recommend(predict_idx)
        # result = recommend(2)

        clothings = Clothing.objects.all()

        context = {
            'coordinateImages': result[0],
            'clothing_kind': result[1],
            'clothings': clothings
        }

    return render(request, 'recommend.html', context)

new_fashion_P/mysite/templates/add_clothing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/grid.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}" />
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/add_clothing.js' %}" defer></script>
    <title>fAIshion_P</title>
  </head>
  <body>
    <aside class="sign-up-aside">
      <div class="sign-up-info">
        <h1 class="sign-up-header">fAIshion_P 회원가입</h1>
        {% if error.state %}
        <h3>{{error.msg}}</h3>
        {% endif %}
        <form action="{% url 'signup' %}" method="post" class="sign-up-content">
          {% csrf_token %}
          <div class="content-item">
            <label class="sign-up-content-label sr-only" for="name">이름: </label>
            <input id="name" class="sign-up-content-input" type="text" name="name" placeholder="이름을 입력해주세요" />
          </div>
          <div class="content-item">
            <label class="sign-up-content-label sr-only" for="id">아이디: </label>
            <input id="id" class="sign-up-content-input" type="text" name="user_id" placeholder="아이디를 입력해주세요" />
          </div>
          <div class="content-item">
            <label class="sign-up-content-label sr-only" for="password">비밀번호:</label>
            <input id="password" class="sign-up-content-input" type="password" name="user_pw" placeholder="비밀번호를 입력해주세요" />
          </div>
          <div class="content-item last-content-item">
            <label class="sign-up-content-label sr-only" for="password">비밀번호 확인:</label>
            <input id="password_check" class="sign-up-content-input" type="password" name="user_pw_check" placeholder="비밀번호를 다시 입력해주세요" />
          </div>
          <div class="button-box">
            <button class="fill-button" type="submit">회원가입</button>
            <button class="fill-button exit-button sign-up-exit-button" type="button">나가기</button>
          </div>
        </form>
      </div>
    </aside>

    <aside class="sign-in-aside">
      <div class="sign-in-info">
        <h1 class="sign-in-header">fAIshion_P 로그인</h1>
        {% if error.state %}
        <h3>{{error.msg}}</h3>
        {% endif %}
        <form class="sign-in-content" action="{% url 'login' %}" method="post">
          {% csrf_token %}
          <div class="content-item">
            <label class="sign-in-content-label" for="sign-in-id">
              <img src="{% static 'assets/id-icon.svg' %}" alt="id-icon" />
            </label>
            <input id="sign-in-id" class="sign-in-content-input" type="text" name="user_id" placeholder="아이디" />
          </div>
          <div class="content-item last-content-item">
            <label class="sign-in-content-label" for="sign-in-password">
              <img src="{% static 'assets/pw-icon.svg' %}" alt="password-icon" />
            </label>
            <input id="sign-in-password" class="sign-in-content-input" type="password" name="user_pw" placeholder="비밀번호" />
          </div>
          <div class="button-box">
            <button type="submit" class="fill-button">로그인</button>
            <button type="button" class="fill-button exit-button sign-in-exit-button">나가기</button>
          </div>
        </form>
      </div>
    </aside>

    {% if user.is_authenticated %}
    <section class="header">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="header-content">
              <h1 class="header-title">
                {{user.username}}님을 위한
                <br />
                코디 추천서비스
              </h1>
              <p class="header-desc">
                이제 머리 아파하지 마세요.
                <br />
                fAIshion_P와 함께라면 당신도 오늘부터 패피!!
              </p>
              <aside class="info-button-box" id="clothings_aside">
                <a href="{% url 'add_clothing' %}">
                  <button class="header-button fill-button" type="button" id="mycloset">내 옷 추가하러 가기</button>
                </a>
                <a href="{% url 'closet' %}">
                  <button class="header-closet-button fill-button" type="button" id="mycloset">내 옷장으로 가기</button>
                </a>
                <input id="mycloth-input" type="hidden" value="{{ request.session.user }}" />
                <a href="{% url 'logout' %}">
                  <button class="logout-button fill-button" type="button">로그아웃</button>
                </a>
                <button class="sr-only signUp-button fill-button" type="button">회원가입</button>
                <button class="sr-only signIn-button fill-button" type="button">로그인</button>
              </aside>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="add-clothing">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="add-clothing-upload">
              <h1 class="add-clothing-upload-title">내 옷 추가하기</h1>
              <form id="id_upload_form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="file-box">
                  <input type="text" class="cloth-upload-name" value="파일선택" disabled="disabled" />
                  <label class="cloth-input-file" for="cloth-input-file">업로드</label>
                  <input id="cloth-input-file" class="cloth-input-file-hidden" type="file" name="image" />
                  <input name="owner" type="hidden" value="{{ request.session.user }}" />
                </div>
                <span class="add-clothing-upload-span">이미지파일을 업로드 해주세요</span>
                <button class="add-clothing-upload-button fill-button" type="submit">옷 추가하기</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% else %}

    <section class="header">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="header-content">
              <h1 class="header-title">
                fAIshion_P님을 위한
                <br />
                코디 추천서비스
              </h1>
              <p class="header-desc">
                이제 머리 아파하지 마세요.
                <br />
                fAIshion_P와 함께라면 당신도 오늘부터 패피!!
              </p>
              <aside class="info-button-box">
                <button class="signUp-button fill-button" type="button">회원가입</button>
                <button class="signIn-button fill-button" type="button">로그인</button>
              </aside>
              <button class="header-button fill-button sr-only" type="button">내 옷 추가하러 가기</button>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endif %}

    <script src="http://code.jquery.com/jquery-latest.js"></script>
  </body>
</html>

new_fashion_P/mysite/templates/backup/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}fAIshion_P{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#decdc3">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">fAIshion_P</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navx`bar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">홈</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'clothing_list' %}">옷장</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

new_fashion_P/mysite/templates/backup/class_clothing_list.html
{% extends 'clothing_list.html' %}

{% comment %} {% block content_header %}
  <h2>옷장</h2>
  <p>
    <a href="{% url 'class_upload_clothing' %}" class="btn btn-primary">내 옷 추가</a>
  </p>
{% endblock %} {% endcomment %}

new_fashion_P/mysite/templates/backup/clothing_list.html
{% extends 'base.html' %}

{% block content %}

  {% block content_header %}
    <h2>옷장</h2>
    <p>
      <a href="{% url 'upload_clothing' %}" class="btn btn-primary">내 옷 추가</a>
    </p>
  {% endblock %}

  <table class="table mb-0">
    <thead>
      <tr>
        <th>옷 사진</th>
        <th>옷 이름</th>
        <th>코디 추천</th>
        <th>삭제</th>
      </tr>
    </thead>
    <tbody>
      {% for clothing in clothings %}
        <tr>
          <td>
            {% if clothing.image %}
              <img src="{{ clothing.image.url }}" alt="{{ clothing.title }}" style="width:150px;">
            {% else %}
              <span class="text-muted">No Images</span>
            {% endif %}
          </td>
          <td>{{ clothing.title }}</td>
          <td>
           <form method="post" action="{% url 'coordinate_clothing' clothing.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-info btn-sm">코디 추천 받기</button>
            </form>
          </td>
          <td>
            <form method="post" action="{% url 'delete_clothing' clothing.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">삭제</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

new_fashion_P/mysite/templates/backup/coordinate_list.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="card-title" style="display: inline-block">당신의&nbsp</h2>
    <h2 style="font-weight: 600; color: red; display: inline-block">{{ clothing_kind }}</h2>
    <h2 style="display: inline-block">와 어울리는 코디입니다.</h2>
    <div id="container" style="display: flex; justify-content: center" >
    {% for coordinateImage in coordinateImages %}
        <div id="item" style="padding: 0 40px">
            <div style="display: flex; flex-direction: column; margin: 30px 0 0 0">
                <img alt="coordinate" src="{{ coordinateImage.c_image.url }}" style="width:220px; height: 300px;">
                <div style="margin: 20px auto;">
                    <a href="{{ coordinateImage.c_url }}" class="btn btn-dark btn-sm" target="_blank">상품 보러 가기</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

new_fashion_P/mysite/templates/backup/home.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="card-title">fAIshion_P고객님들을 위한 코디 추천 서비스</h2>
  <br/>
  <br/>
  <br/>
  <br/>
  <p class="card-text">옷장에 자신의 옷들을 넣어두시면 빠르게 코디 추천을 받을 수 있습니다. </p>
  <br/>
  <p class="card-text">
    이제 머리 아파하지 마세요. fAIshion_P와 함께라면 당신도 오늘부터 패피!!<br>
    <a href="https://github.com/wlghsp/fAIshion_P">@fAIshion_P</a>
  </p>
{% endblock %}

new_fashion_P/mysite/templates/backup/upload_clothing.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>내 옷 추가</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">추가</button>
  </form>
{% endblock %}

new_fashion_P/mysite/templates/closet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/grid.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}" />
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/closet.js' %}" defer></script>
    <title>fAIshion_P</title>
  </head>
  <body>
    <aside class="sign-up-aside">
      <div class="sign-up-info">
        <h1 class="sign-up-header">fAIshion_P 회원가입</h1>
        {% if error.state %}
        <h3>{{error.msg}}</h3>
        {% endif %}
        <form action="{% url 'signup' %}" method="post" class="sign-up-content">
          {% csrf_token %}
          <div class="content-item">
            <label class="sign-up-content-label sr-only" for="name">이름: </label>
            <input id="name" class="sign-up-content-input" type="text" name="name" placeholder="이름을 입력해주세요" />
          </div>
          <div class="content-item">
            <label class="sign-up-content-label sr-only" for="id">아이디: </label>
            <input id="id" class="sign-up-content-input" type="text" name="user_id" placeholder="아이디를 입력해주세요" />
          </div>
          <div class="content-item">
            <label class="sign-up-content-label sr-only" for="password">비밀번호:</label>
            <input id="password" class="sign-up-content-input" type="password" name="user_pw" placeholder="비밀번호를 입력해주세요" />
          </div>
          <div class="content-item last-content-item">
            <label class="sign-up-content-label sr-only" for="password">비밀번호 확인:</label>
            <input id="password_check" class="sign-up-content-input" type="password" name="user_pw_check" placeholder="비밀번호를 다시 입력해주세요" />
          </div>
          <div class="button-box">
            <button class="fill-button" type="submit">회원가입</button>
            <button class="fill-button exit-button sign-up-exit-button" type="button">나가기</button>
          </div>
        </form>
      </div>
    </aside>

    <aside class="sign-in-aside">
      <div class="sign-in-info">
        <h1 class="sign-in-header">fAIshion_P 로그인</h1>
        {% if error.state %}
        <h3>{{error.msg}}</h3>
        {% endif %}
        <form class="sign-in-content" action="{% url 'login' %}" method="post">
          {% csrf_token %}
          <div class="content-item">
            <label class="sign-in-content-label" for="sign-in-id">
              <img src="{% static 'assets/id-icon.svg' %}" alt="id-icon" />
            </label>
            <input id="sign-in-id" class="sign-in-content-input" type="text" name="user_id" placeholder="아이디" />
          </div>
          <div class="content-item last-content-item">
            <label class="sign-in-content-label" for="sign-in-password">
              <img src="{% static 'assets/pw-icon.svg' %}" alt="password-icon" />
            </label>
            <input id="sign-in-password" class="sign-in-content-input" type="password" name="user_pw" placeholder="비밀번호" />
          </div>
          <div class="button-box">
            <button type="submit" class="fill-button">로그인</button>
            <button type="button" class="fill-button exit-button sign-in-exit-button">나가기</button>
          </div>
        </form>
      </div>
    </aside>

    {% if user.is_authenticated %}
    <section class="header">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="header-content">
              <h1 class="header-title">
                {{user.username}}님을 위한
                <br />
                코디 추천서비스
              </h1>
              <p class="header-desc">
                이제 머리 아파하지 마세요.
                <br />
                fAIshion_P와 함께라면 당신도 오늘부터 패피!!
              </p>
              <aside class="info-button-box" id="clothings_aside">
                <a href="{% url 'add_clothing' %}">
                  <button class="header-button fill-button" type="button" id="mycloset">내 옷 추가하러 가기</button>
                </a>
                <input id="mycloth-input" type="hidden" value="{{ request.session.user }}" />
                <a href="{% url 'closet' %}">
                  <button class="header-closet-button fill-button" type="button" id="mycloset">내 옷장으로 가기</button>
                </a>
                <a href="{% url 'logout' %}">
                  <button class="logout-button fill-button" type="button">로그아웃</button>
                </a>
                <button class="sr-only signUp-button fill-button" type="button">회원가입</button>
                <button class="sr-only signIn-button fill-button" type="button">로그인</button>
              </aside>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="add-clothing">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="add-clothing-upload">
              <h1 class="add-clothing-upload-title">내 옷 추가하기</h1>
              <form id="id_upload_form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="file-box">
                  <input type="text" class="cloth-upload-name" value="파일선택" disabled="disabled" />
                  <label class="cloth-input-file" for="cloth-input-file">업로드</label>
                  <input id="cloth-input-file" class="cloth-input-file-hidden" type="file" name="image" />
                  <input name="owner" type="hidden" value="{{ request.session.user }}" />
                </div>
                <span class="add-clothing-upload-span">이미지파일을 업로드 해주세요</span>
                <button class="add-clothing-upload-button fill-button" type="submit">옷 추가하기</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="closet add-clothing">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="add-clothing-box">
              <h1 class="add-clothing-box-title">옷장</h1>
              <span>코디 추천을 누르시면 해당 아이템의 코디를 추천해드려요.</span>
              <dl class="add-clothing-box-content slide-list">
                {% for clothing in clothings %}
                <div class="add-clothing-box-content-item slide-content">
                  <div class="add-clothing-box-content-image">
                    <dt class="sr-only">옷 사진</dt>
                    {% if clothing.image %}
                    <dd>
                      <img src="{{ clothing.image.url }}" alt="{{ clothing.image.url }}" />
                    </dd>
                    {% endif %}
                  </div>
                  <div class="add-clothing-box-content-buttons">
                    <div>
                      <dt class="sr-only">코디 추천하기</dt>
                      <dd>
                        <form method="post" action="{% url 'coordinate_clothing' clothing.pk %}">
                          {% csrf_token %}
                          <button class="add-clothing-box-button fill-button" type="submit">코디 추천</button>
                        </form>
                      </dd>
                    </div>
                    <div>
                      <dt class="sr-only">삭제하기</dt>
                      <dd>
                        <form method="post" action="{% url 'delete_clothing' clothing.pk %}">
                          {% csrf_token %}
                          <button class="delete-button fill-button" type="submit">삭제</button>
                        </form>
                      </dd>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </dl>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% else %}

    <section class="header">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="header-content">
              <h1 class="header-title">
                fAIshion_P님을 위한
                <br />
                코디 추천서비스
              </h1>
              <p class="header-desc">
                이제 머리 아파하지 마세요.
                <br />
                fAIshion_P와 함께라면 당신도 오늘부터 패피!!
              </p>
              <aside class="info-button-box">
                <button class="signUp-button fill-button" type="button">회원가입</button>
                <button class="signIn-button fill-button" type="button">로그인</button>
              </aside>
              <button class="header-button fill-button sr-only" type="button">내 옷 추가하러 가기</button>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endif %}

    <script src="http://code.jquery.com/jquery-latest.js"></script>
  </body>
</html>